name: Deploy Next.js to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build Next.js app
      run: npm run build

    - name: Move standalone output
      run: |
        mkdir -p output
        cp -r .next/standalone/* output/
        if [ -d ".next/static" ]; then cp -r .next/static output/.next/; fi
        if [ -d "public" ]; then cp -r public output/; fi
        cp package.json output/

    - name: Zip output
      run: cd output && zip -r ../app.zip .

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: nextjs-hello-world
        package: ./app.zip