name: Trigger Azure Pipeline on Tag or PR

on:
  push:
    tags:
      - "*"
  pull_request:

jobs:
  trigger-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Azure Pipeline
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.AZURE_DEVOPS_AUTH }}" \
            -H "Content-Type: application/json" \
            --data '{"resources":{}}' \
            https://dev.azure.com/Assignment-DevOps/Next%20js%20Hello%20world%20Application/_apis/pipelines/11/runs?api-version=7.1-preview.1